# see https://docs.silverstripe.org/en/developer_guides/configuration/configuration/

Silverstripe\SiteConfig\SiteConfig:
  extensions:
    - Atwx\ProjectInfo\Extensions\ProjectInfoExtension

SilverStripe\SiteConfig\SiteConfigLeftAndMain:
  extensions:
    - Atwx\ProjectInfo\Extensions\LeftAndMainBackupExport
